## CAR PRICE PREDICTION SYSTEM (A2), Nirut Gammayeengoen, st123472

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import mlflow
import os

mlflow.set_tracking_uri('http://localhost:5000')

os.environ['LOGNAME'] = "nirut"

mlflow.set_experiment(experiment_name="nirut-practice_v0")

<Experiment: artifact_location='mlflow-artifacts:/327292435919509977', creation_time=1695534036739, experiment_id='327292435919509977', last_update_time=1695534036739, lifecycle_stage='active', name='nirut-practice_v0', tags={}>

In [3]:
from sklearn.datasets import load_diabetes

diabetes = load_diabetes()

print('Features: ', diabetes.feature_names)

Features:  ['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']


In [4]:
X = diabetes.data
X.shape

m = X.shape[0]
n = X.shape[1]

print(m, n)

442 10


In [5]:
y = diabetes.target
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [6]:
assert m == y.shape[0]

### 1.2 Train Test split data

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

assert len(X_train) == len(y_train)
assert len(X_test)  == len(y_test)

In [8]:
print(f'len(X_train): {len(X_train)}')
print(f'len(y_train): {len(y_train)}')
print(f'len(X_test): {len(X_test)}')
print(f'len(y_test): {len(y_test)}')

len(X_train): 309
len(y_train): 309
len(X_test): 133
len(y_test): 133


In [9]:
X_train

array([[-0.00914709,  0.05068012,  0.00133873, ..., -0.00259226,
         0.02671684,  0.08176444],
       [ 0.04534098,  0.05068012, -0.03530688, ..., -0.00259226,
         0.01556846,  0.0569118 ],
       [-0.09269548,  0.05068012, -0.0902753 , ..., -0.00259226,
         0.02405509,  0.00306441],
       ...,
       [ 0.01628068, -0.04464164,  0.01750591, ..., -0.00259226,
         0.03723625, -0.0010777 ],
       [-0.03094232, -0.04464164,  0.04660684, ..., -0.00259226,
         0.06345272, -0.02593034],
       [-0.00551455, -0.04464164,  0.0433734 , ..., -0.00259226,
         0.04234098, -0.01764613]])

In [10]:
X_test

array([[-0.00188202,  0.05068012, -0.03315126, ...,  0.01991742,
         0.01022672,  0.02791705],
       [ 0.04897352, -0.04464164, -0.04285156, ..., -0.00259226,
        -0.02595311, -0.0632093 ],
       [-0.01641217,  0.05068012,  0.12744274, ...,  0.03430886,
         0.03486619,  0.00306441],
       ...,
       [-0.04183994, -0.04464164,  0.12852056, ..., -0.03949338,
        -0.01599887, -0.05078298],
       [-0.01641217, -0.04464164, -0.05255187, ..., -0.03949338,
        -0.06833155, -0.03007245],
       [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
         0.03606033, -0.04249877]])

### 1.3 Feature scale data to reach faster convergence

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [12]:
print(f'X_train: \n{X_train}')
print()
print(f'X_train.shape: {X_train.shape}')
print()
print(f'X_test: \n{X_test}')
print()
print(f'X_test.shape:  {X_test.shape}')

X_train: 
[[-0.21950867  1.05661647 -0.01722226 ... -0.09736811  0.48864966
   1.61667584]
 [ 0.97464942  1.05661647 -0.78066982 ... -0.09736811  0.26217517
   1.11131131]
 [-2.05055108  1.05661647 -1.92584116 ... -0.09736811  0.43457725
   0.01635484]
 ...
 [ 0.3377651  -0.9464172   0.31959284 ... -0.09736811  0.70234676
  -0.06787258]
 [-0.69717191 -0.9464172   0.92586002 ... -0.09736811  1.23492291
  -0.57323711]
 [-0.13989813 -0.9464172   0.858497   ... -0.09736811  0.80604726
  -0.40478227]]

X_train.shape: (309, 10)

X_test: 
[[-0.06028759  1.05661647 -0.73576114 ...  0.37010299  0.15366
   0.52171936]
 [ 1.05425996 -0.9464172  -0.9378502  ... -0.09736811 -0.5813173
  -1.3312839 ]
 [-0.37872975  1.05661647  2.60993552 ...  0.66897796  0.6542001
   0.01635484]
 ...
 [-0.93600353 -0.9464172   2.63238986 ... -0.86371419 -0.37910132
  -1.07860163]
 [-0.37872975 -0.9464172  -1.13993926 ... -0.86371419 -1.44221664
  -0.65746453]
 [-1.17483515  1.05661647 -0.42140038 ...  2.20167012  0.

### 1.4 Add intercepts

In [13]:
intercept = np.ones((X_train.shape[0], 1))
X_train   = np.concatenate((intercept, X_train), axis=1)
intercept = np.ones((X_test.shape[0], 1))
X_test    = np.concatenate((intercept, X_test), axis=1)

In [14]:
print(f'X_train: \n{X_train}')
print()
print(f'X_train.shape: {X_train.shape}')
print()
print(f'X_test: \n{X_test}')
print()
print(f'X_test.shape:  {X_test.shape}')

X_train: 
[[ 1.         -0.21950867  1.05661647 ... -0.09736811  0.48864966
   1.61667584]
 [ 1.          0.97464942  1.05661647 ... -0.09736811  0.26217517
   1.11131131]
 [ 1.         -2.05055108  1.05661647 ... -0.09736811  0.43457725
   0.01635484]
 ...
 [ 1.          0.3377651  -0.9464172  ... -0.09736811  0.70234676
  -0.06787258]
 [ 1.         -0.69717191 -0.9464172  ... -0.09736811  1.23492291
  -0.57323711]
 [ 1.         -0.13989813 -0.9464172  ... -0.09736811  0.80604726
  -0.40478227]]

X_train.shape: (309, 11)

X_test: 
[[ 1.         -0.06028759  1.05661647 ...  0.37010299  0.15366
   0.52171936]
 [ 1.          1.05425996 -0.9464172  ... -0.09736811 -0.5813173
  -1.3312839 ]
 [ 1.         -0.37872975  1.05661647 ...  0.66897796  0.6542001
   0.01635484]
 ...
 [ 1.         -0.93600353 -0.9464172  ... -0.86371419 -0.37910132
  -1.07860163]
 [ 1.         -0.37872975 -0.9464172  ... -0.86371419 -1.44221664
  -0.65746453]
 [ 1.         -1.17483515  1.05661647 ...  2.20167012  0.

In [15]:
X_train.shape[1]

11

In [16]:
# Check sample of X_train must = sample of y_train
assert X_train.shape[0] == y_train.shape[0]

### 1.5 Feature Engineering (optional)

## Step 2: Fit model

### 2.1 Define algorithm

In [17]:
from time import time

assert X_train.shape[0] == y_train.shape[0]

theta = np.zeros(X_train.shape[1]) # initial weight (theta)
lr = 0.1
epochs = 50

def h_theta(X, theta):
    return X @ theta

def mse(yhat, y):
    m = yhat.shape[0] # m: number of samples
    return ((yhat - y) ** 2).sum() / m
    # return ((yhat - y) ** 2).sum() / yhat.shape[0]


def r2(yhat, y):
    ssr = ((y - yhat) ** 2).sum() # ssr: residual sum of squares
    ybar = y.mean()
    sst = ((y - ybar) ** 2).sum() # sst: total sum of squares
    r2_score = 1 - (ssr / sst)
    return r2_score

def gradient(X, error):
    m = X.shape[0] # m: number of samples
    return (X.T @ error) / m
    # return (X.T @ error) / X.shape[0]


# ------------------------- fitting area ------------------------
start_time = time()

for i in range(epochs):

    print(f'epoch: {i}')

    # Step 1: Predict
    # 1. yhat = X @ w
    # prediction
    # yhat (m, ) = (m, n) @ (n, )

    # Add for I want to know
    print(f'X_train = {X_train}')
    print(f'X_train.shape = {X_train.shape}')
    print(f'theta = {theta}')
    print(f'theta.shape = {theta.shape}')

    yhat = h_theta(X_train, theta)

    # Add for I want to know
    print(f'yhat    = {yhat}')
    print(f'yhat.shape = {yhat.shape}')
    print(f'y_train = {y_train}')
    print(f'y_train.shape = {y_train.shape}')

    # Step 2: Error
    # error for use to calculate gradients
    # error (m, ) = (m, ) - (m, )
    error = yhat - y_train
    print(f'error = {error}')
    print(f'error.shape = {error.shape}')

    # Step 3: Gradient
    # grad (n, ) = (n, m) @ (m, )
    # grad for each feature j
    grad = gradient(X_train, error)
    print(f'grad = {grad}')
    print(f'grad.shape = {grad.shape}')

    # Step 4: Update w
    # w = w - lr * grad
    # w (n, ) = (n, ) - scalar * (n, )
    theta = theta - lr * grad
    print(f'update theta: \n{theta}')
    print(f'update theta.shape = {theta.shape}')
    
    print('----------------------------')

time_taken = time() - start_time

epoch: 0
X_train = [[ 1.         -0.21950867  1.05661647 ... -0.09736811  0.48864966
   1.61667584]
 [ 1.          0.97464942  1.05661647 ... -0.09736811  0.26217517
   1.11131131]
 [ 1.         -2.05055108  1.05661647 ... -0.09736811  0.43457725
   0.01635484]
 ...
 [ 1.          0.3377651  -0.9464172  ... -0.09736811  0.70234676
  -0.06787258]
 [ 1.         -0.69717191 -0.9464172  ... -0.09736811  1.23492291
  -0.57323711]
 [ 1.         -0.13989813 -0.9464172  ... -0.09736811  0.80604726
  -0.40478227]]
X_train.shape = (309, 11)
theta = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
theta.shape = (11,)
yhat    = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 

In [ ]:
X_test, X_test.shape

In [ ]:
y_test, y_test.shape

In [ ]:
yhat, yhat.shape

In [ ]:
# Check theta
print(f'theta: {theta}')
print(f'theta.shape: {theta.shape}')

## 2.2 Compute accuracy/loss

In [ ]:
# Now got lovely w, it's time to check our accuracy

# 1. Make prediction
yhat = h_theta(X_test, theta)

# 2.1 Calculate mean squared errors
mse = mse(yhat, y_test)

# 2.2 Calculate r2 score
r2 = r2(yhat, y_test)

# Print the mse and r2
print('MSE: ', mse)shape
print('r2: ', r2)
print("Time used: ", time_taken)

In [ ]:
# Check theta
print(f'theta: {theta}')

# Some graphs

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(5,5))
plt.scatter(y_test, yhat, c='crimson')

p1 = max(max(yhat), max(y_test))
p2 = min(min(yhat), min(y_test))
plt.plot([p1, p2], [p1, p2], 'b-')
plt.xlabel('True Values', fontsize=15)
plt.ylabel('Predictions', fontsize=15)
plt.axis('equal')
plt.show()